#include <random>
#include "integrators.h"
#include "base.h"

//int Atom::num_of_atoms = 0;
int Base::box_dim = 5;
int Base::num_of_atoms = 2;
int Base::iterations = 20;

int main(int argc, char *argv[]){

    int num = 5;
    double energy;

    Eigen::Vector2d force;

    Atom **atoms;
    atoms = (Atom**) malloc(num * sizeof(Atom*));
    Frame **frames;
    frames = (Frame**) malloc(Base::iterations * sizeof(Frame*));

    //Initializer
    for(int i = 0; i < Base::num_of_atoms; i++){
        atoms[i] = new Atom();
        atoms[i]->pos[0] = rand() * Base::box_dim;
        atoms[i]->pos[1] = rand() * Base::box_dim;
        atoms[i]->pos[2] = 0;

        atoms[i]->vel[0] = rand();
        atoms[i]->vel[1] = rand();
        atoms[i]->vel[2] = 0;

        atoms[i]->old_force[0] = 0;
        atoms[i]->old_force[1] = 0;
        atoms[i]->old_force[2] = 0;
    }
    for(int i = 0; i < Base::iterations; i++){
        integrators::velocityVerlet(atoms);
        printf("Iteration %i\n", i);
        frames[i] = new Frame();
        //frames[i]->saveCoordinates(atoms);
        if(i % 2 == 0){
            //std::cout << "asd" << std::endl;
        }
    }
    return 0;
}

// void writeCoordinates(){
//     int i = 0;
//     FILE *f = fopen(name, "w");
//     if(f == NULL){
//         printf("Can't open file!\n");
//         exit(1);
//     }
//     fprintf(f, "Generated by Slaymulator.\n");
//     fprintf(f, "%d\n", Particle::numOfParticles);
//     for(i = 0; i < Particle::numOfParticles; i++){
//         fprintf(f, "%5d%-5s%5s%5d%8.3f%8.3f%8.3f\n", 1, "ion", particles[i]->name, i, particles[i]->com[0]/10, particles[i]->com[1]/10, particles[i]->com[2]/10);
//     }
//     fprintf(f, "%lf    %lf     %lf\n", Base::xL/10, Base::yL/10, Base::zL/10);
//     fclose(f);
// }
